### ISSUE TITLE
Implement "playtop" command

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#10]
Allows for pushing songs to the top of the queue to be played up next.

### Usage
* `!playtop <song>` pushes a new track to the top of the queue.

### Notes
* If the bot isn't playing anything, the command should push to the first position.
* However, if it is currently playing, it should place the new track in the queue's **second position** as the topmost element will be the track that's now playing.

**Comment by Antonio-Bennett** [comment]
Hi! I never worked on a discord bot before so I would love to try and solve this issue :)

**Comment by Antonio-Bennett** [comment]
That is definitely what I'm looking for! Can't believe I missed it 😭 Thanks a lot :)

**Comment by aquelemiguel** [comment]
> Hey submitted PR #24 :)

Awesome, I'll take a look at it and give you feedback ASAP. 🚀
