### ISSUE TITLE
Env flag to register app commands to guild

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#100]
Since the introduction of slash commands on #89, new commands have been harder to test because [new global application commands are only available in guilds after 1 hour](https://docs.rs/serenity/latest/serenity/http/client/struct.Http.html#method.create_global_application_command). It doesn't seem right that we have to wait this much time while developing or reviewing PRs.

I also dislike using [`create_guild_application_commands`](https://docs.rs/serenity/latest/serenity/http/client/struct.Http.html#method.create_guild_application_commands) momentarily and having to remember to replace it in the end. Also I'm too lazy to edit someone's PR locally to use guild commands.

Perhaps we could have some sort of debug flag that, when used, registered commands to the provided guild. Otherwise, it'd register to the global Discord command framework.

**Comment by joao-conde** [comment]
You can change it once, stash the changes with git and pop it when you are working locally. Does not seem to be a huge hassle

**Comment by afonsojramos** [comment]
This is only relative to new commands right? I think that this is just something that we have to keep in mind when reviewing and when developing. 🤔

**Comment by aquelemiguel** [comment]
Thank you for your inputs guys, I'll close it for now.
