### ISSUE TITLE
Clean messages after delay

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#11]
A toggle that makes Parrot clean after itself. For each message Parrot sends, after the specified delay it cleans both response and request messages. **It should only be callable by guild members with the Manage Messages permission**.

### Usage
* `!autoclean` defaults the delay to something like 5 seconds
* `!autoclean <delay in seconds>`

**Comment by aquelemiguel** [comment]
In retrospect, I don't personally see the need for a command like this and I'm a bit reticent how Parrot would handle editing potentially deleted messages (I suppose we should keep this in mind regardless).

Also, would it make sense deleting queue messages given that they live update? I think this change would add unneeded complexity to the code and I'm in favor of closing this issue if you're as well, @joao-conde & @afonsojramos.

**Comment by joao-conde** [comment]
We have and most servers will have a specific command for bots. So I would say we can close this.

**Comment by afonsojramos** [comment]
In the case of big servers the original message can get lost quite quickly, so I still think this would be a welcome feature, even if we don't develop it right away.

As for the commands for bots, I'm not so sure that servers have message cleaning specific for bots. Maybe for whole channels, but I haven't seen it for bots in specific.

**Comment by aquelemiguel** [comment]
Thank you both for your inputs. I think @joao-conde meant servers usually have a dedicated text channel for music bots?
IDK, this is a music bot, I don't see the need for cleaning - there are plenty of bots out there that already do this.

I'm closing it as not planned for the time being.
