### ISSUE TITLE
Playing songs on a different channel

### ISSUE THREAD

**Issue by afonsojramos** [aquelemiguel/parrot#116]
Playing songs while on a different channel than the bot should not be possible. This is a blocker for big servers with a lot of voice rooms.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Not being able to send play commands to a bot that is in a different channel. |
| **Observed** | Ability to send play commands to a bot that is not in the same channel as the user. |

## Repro Steps

1. Sending a play command to the bot when in a different channel.
2. Works 😢

**Comment by aquelemiguel** [comment]
Good catch, we should even expand this to basically all commands?

**Comment by aquelemiguel** [comment]
@afonsojramos I get what you say, but still feels a little weird to be capable of skipping a song that's playing on another channel.
Maybe others can chime in on which commands fit this restriction. #119 is currently just for `/play`.

**Comment by afonsojramos** [comment]
That's also true...
