### ISSUE TITLE
`/summon` should always move the bot to the summoner's channel

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#120]
If the bot is already connected to another voice channel, `/summon` replies with "I'm already here!".
This is not very accurate. The bot should not fail and move to the summoner's channel.

![image](https://user-images.githubusercontent.com/5618493/151185715-103ac82d-6cbc-4521-ac12-736c9b3a4dec.png)

**Comment by afonsojramos** [comment]
> The bot should not fail and move to the summoner's channel.

Are we sure this is the intended action? What if the bot is playing something for someone else? I think that it should continue to not move the bot on command.

**Comment by aquelemiguel** [comment]
> What if the bot is playing something for someone else?

Yeah, I can see that being annoying. I'll just change the message to say it's already on another channel.
