### ISSUE TITLE
Add `DISCORD_APPID` to docs + Better error message for missing env variables

### ISSUE THREAD

**Issue by UnlimitedCookies** [aquelemiguel/parrot#131]
## Description

The bot doesn't start and shows this message instead and immediately exits:
```
Error: NotPresent
```
I've tried both the ghcr.io image and also compiled it from git with the newest rust nightly version.
The DISCORD_TOKEN env variable was set.

## Expected vs. Observed

It's expected to start or show a helpful error message.

## Repro Steps

1. Download the current docker image and run it
2. Start the bot

## Environment

| Key | Value |
| --- | --- |
| **Operating System** | Arch Linux|

**Comment by afonsojramos** [comment]
Hi @UnlimitedCookies! 

The `Error: NotPresent` shows up when one of the environment variables is not set.
Did you also set `DISCORD_APPID`? You need both env vars.

**Comment by UnlimitedCookies** [comment]
Oh, yep - that fixed the issue.
You should definitely add this to the documentation. Also, the error message could be a little more helpful imo.

**Comment by afonsojramos** [comment]
Truly thought we had that, will update!

Thanks for the issue @UnlimitedCookies!

**Comment by UnlimitedCookies** [comment]
Awesome! Perhaps you could also add it to the `Readme.md` for now?

Later down the road, I suggest adding a wiki page with all the possible environment variables.

**Comment by afonsojramos** [comment]
I already updated the Wiki (Step 7), but will also make a revision to the `readme.md` in my PR, thanks!
