### ISSUE TITLE
Skip vote count takes everyone into account

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#136]
## Description

Currently, the skip vote takes into account the number of people connected to any voice channel in the guild, and not the people connected to the voice channel the bot is in.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The bot only takes into account the number of people connected to the same voice channel as itself. |
| **Observed** | The bot takes is counting anyone currently in a voice channel. |

## Repro Steps

1. Join a voice channel when other voice channels also have members.
2. Have the bot play a video.
3. Vote to skip the currenlty playing video.
4. Observe that the number of required votes isn't half of the members in the same voice channel.

## Environment

Key | Value
-- | --
Operating System | Ubuntu 21.10 impish
Kernel | x86_64 Linux 5.13.0-28-generic
CPU | Intel Core i5-6500 @ 4x 3,6GHz
RAM | 15893MiB

## Screens

![image](https://user-images.githubusercontent.com/6492427/152707570-e6b1d450-af65-4da0-88fa-4b8e157fc8e4.png)

**Comment by afonsojramos** [comment]
Well, knowing where the bug is is easy [skip.rs#L35](https://github.com/aquelemiguel/parrot/blob/main/src/commands/skip.rs#L35), I'll need to investigate how to fix it, but it should revolve around checking which ones are connected to the same channel.
