### ISSUE TITLE
Prevent searches from being processed by playlist focused commands

### ISSUE THREAD

**Issue by StaticRocket** [aquelemiguel/parrot#145]
I completely forgot about this edge case in my last PR. If a search gets passed to ytdl with `/play (all, reverse, etc.)` it will silently fail.

```
ERROR: [generic] 'echo' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:echo" ) to search YouTube
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/commands/play.rs:97:35
```

Should a message be sent to inform the user that these commands only accept links?

**Comment by aquelemiguel** [comment]
Hey again, @StaticRocket! Should already be handled in #144. 🙂
