### ISSUE TITLE
Any `/play` subcommand causes panic when enqueuing a playlist

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#147]
## Description

When using any `/play` subcommand with a playlist, a panic occurs.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The playlist is queued. |
| **Observed** | Nothing happens. |

## Repro Steps

1. Use any  `/play` subcommand with a playlist.
2. Observe nothing happened by running `/queue` after a while.

## Environment

Key | Value
-- | --
Operating System | Ubuntu 21.10 impish
Kernel | x86_64 Linux 5.13.0-28-generic
CPU | Intel Core i5-6500 @ 4x 3,6GHz
RAM | 15893MiB

## Screens

```
fev 17 14:11:21 rho parrot[219829]: thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', src/commands/play.rs:281:36
```

**Comment by afonsojramos** [comment]
Which of the `/play` commands was used?

 If you used old play command without any subcommand specification, it was probably because Discord was still updating the commands, because now there is no `/play` command.
 
The new normal play command should be `/play end`.

**Comment by rafaeldamasceno** [comment]
@afonsojramos Sorry I wasn't so clear. I first observed the issue on `/play jump` and thought the issue was restricted to that subcommand, but I have since understood every `/play` subcommand is affected. When rewording from the `jump` subcommand, I didn't make it clear. I have now reworded it again and it should be clear now that it affects every subcommand.

**Comment by rafaeldamasceno** [comment]
This was a regression caused by 6eb5e6bcd60a625da3c9f02e75d370387d2e333a.

**Comment by afonsojramos** [comment]
Oh, okay, this is actually easily fixable. The problem is that said code is not unreachable at all since the `query_type` is passed along from `enqueue_playlist` to `enqueue_song`.
