### ISSUE TITLE
Destructive `/play` subcommands aren't restricted

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#148]
## Description

Some newly added `/play` subcommands have destructive effects on the queue and should be restricted to DJ role members to keep in line with the other commands that do the same thing. They are `/play next` and `/play jump`.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The commands should be restricted to DJ role members. |
| **Observed** | The commands are unrestriced. |

## Repro Steps

1. Make sure you don't have the DJ role.
2. Verify you are able to use the `/play next` and `/play jump` subcommands.

## Environment

Key | Value
-- | --
Operating System | Ubuntu 21.10 impish
Kernel | x86_64 Linux 5.13.0-28-generic
CPU | Intel Core i5-6500 @ 4x 3,6GHz
RAM | 15893MiB

**Comment by afonsojramos** [comment]
This is definitely something worth raising a discussion for. Permissions can only be set at a command level, therefore, since `next`, `end`, `jump`, etc. are subcommands, we cannot, at the moment, set different permissions to different subcommands.

If we do want to make these restrictions, the only solution that I can imagine at the moment is by splitting the playlist and normal videos commands... Do you see any alternatives @aquelemiguel @joao-conde?

**Comment by rafaeldamasceno** [comment]
I’ve said before that I don’t really use the DJ role, so if this is what you expect from it, then I’m fine with it, especially if #146 is implemented. Another possibility is to only restrict the advanced play commands group and keep the default open, but again, as long as I have the option to disable DJ, they could all be restricted. I’m just going to bring attention to this one last time: is there really no way to have the base play command work if there are subcommands?

**Comment by aquelemiguel** [comment]
> I’m just going to bring attention to this one last time: is there really no way to have the base play command work if there are subcommands?

Absolutely not possible, check the [red box in the docs](https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups).

**Comment by rafaeldamasceno** [comment]
Well, that’s that, then. I really think the `/play end` nomenclature is really weird and confusing, even for anyone that has been regularly using Discord music bots, so I’m in favor of moving the subcommands to a `/superplay` base command (which is now my favorite name. Thanks @afonsojramos, although I may be influeced by the MacBook I’ve started using :P).

**Comment by aquelemiguel** [comment]
Let's hear it from the rest of the contributors, but I completely agree with you here.
@afonsojramos @joao-conde If we're all on the same page, let's re-open #151 to perform these changes.

**Comment by joao-conde** [comment]
Go for it
