### ISSUE TITLE
`/play end` should just be `/play`

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#149]
## Rationale

The `/play end` suncommand should still be named the same, since it performs exactly the same as the old `/play`. Having it as subcommand creates confusion, since it isn't obvious that `end` refers to the main play command with the default and expected behavior.

## Description

Rework the subcommand `/play end` into the old `/play`.

## Addendum

I'm not sure whether the existence of subcommands implies that the parent command cannot be called standalone. If that's the case, I'd very much suggest the current subcommands be moved to a different parent command and keeping the `/play` command as is.

**Comment by afonsojramos** [comment]
Okay, I just proposed this to be the solution to #148, so I think we can kill two birds with one stone here as I agree that we should keep the normal `play` command as simply `/play`.

**Comment by rafaeldamasceno** [comment]
> What name should we give to this advanced play command? How about `/splay` for "super play"?

That's a good suggestion (although in my mind it was suggested from "special play"). Another alternative is "advanced play", so `/aplay`, `/advplay` or any other variant.

**Comment by danrpinho** [comment]
> What name should we give to this advanced play command? How about `/splay` for "super play"?

I feel that using `/splay` would be inconsistent with other commands such as, for example, `/forceskip`. I wouldn't mind if this advanced play command had a longer name (like `/superplay` or `/advancedplay`), since Discord has an autocomplete function and we could just use tab-complete to access it.

**Comment by aquelemiguel** [comment]
@danrpinho I really like `/superplay`!
