### ISSUE TITLE
SponsorBlock integration

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#15]
[SponsorBlock](https://sponsor.ajay.app/) is an open-source crowdsourced browser extension and open API for skipping sponsor segments in YouTube videos. It also keeps track of non-music segments for music videos.

The idea would be enqueueing a song, using the API to search for non-music segments (e.g., cinematic parts in music videos, credits or intermissions) and automatically skip them when the playtime enters that segment.

### Possible usage
* `!sponsorblock` as an on/off toggle for this feature

### Implementation
Triggering the seek action at specific timestamps might raise some issues.
* Should the bot periodically (every second or less) fire an event checking whether the song entered a non-music segment?
* We could also schedule events for those specific timestamps but we'd have to be extra careful adjusting the scheduling because of time altering commands like `!pause` and `!seek`.
* ...

**Comment by aquelemiguel** [comment]
Just found out [yt-dlp supports SponsorBlock](https://github.com/yt-dlp/yt-dlp#sponsorblock-options) and you can remove certain categories. No need for FFmpeg gimmicks.

However, in order to run our own custom yt-dlp commands, we'd need to ditch `Restartable::ytdl` - instead download the song and pass it to `Restartable::ffmpeg`.

![image](https://user-images.githubusercontent.com/5618493/149972157-eb8a8014-2c10-4756-b8b2-672798dde926.png)

As an added bonus, supporting custom yt-dlp (or FFmpeg) commands might help us fix #88.

**Comment by joao-conde** [comment]
We have to see what `Restartable::ytdl` does again, with a proper look. If it simply uses `yt-dlp` for metadata and pipes that to `Restartable::ffmpeg` then it will be easy.

**Comment by aquelemiguel** [comment]
After experimenting for a few days, this revealed itself to be tougher than initially expected. This is because yt-dlp only does the Sponsorblock step after downloading the video. That's terrible because it now forces us to first download the track, trim it and then stream it (and I guess eventually delete it). Too much hassle for a small niche feature.

If we ever add playback support for local files, then we can revisit this. Closing it for now.
