### ISSUE TITLE
Add range end to `/remove`

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#155]
## Rationale

Sometimes you want to remove an entire range of songs from the queue.

## Description

Add an optional positive integer range end parameter. When set, instead of removing a single track from the queue, remove all tracks in the given range.

**Comment by afonsojramos** [comment]
How should this be displayed to the user? 

Right now we have this: 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/19473034/155311725-793b16e3-3342-4303-bd0d-07f55806541a.png">

The index is currently the only parameter and is required (obviously), should we simply add an optional `until` (other name suggestions accepted) parameter to ask for the end of the range?

**Comment by aquelemiguel** [comment]
An optional parameter sounds good! May I suggest renaming `index` to `start` and introducing `end`?

**Comment by afonsojramos** [comment]
@aquelemiguel this is the same problem as with the skip optional. I sort of disagree with renaming `index` to `start`, because if you are simply removing one of the tracks it is not the start of anything. The range removal is a feature that only exists if the `until` optional is sent.

**Comment by aquelemiguel** [comment]
I don't see "start" as necessarily needing an "end" to make sense, but I see your concern. "until" is fine as well. 🙂

**Comment by rafaeldamasceno** [comment]
I like `index` and `until`, mainly for the reasons @afonsojramos has described. Personally, I don't even think that the `index` tooltip needs to be changed, unless you want to do some "Position of the (starting) track (...)" shenanigans. I'd rather have the `until` tooltip be more descriptive:

> If set, remove a range of tracks from index until the one set here instead.

**Comment by afonsojramos** [comment]
1. Add a subsequent track position to remove a range of tracks.
2. If set, remove a range of tracks from index until the one set here instead.

I also considered a variation of 2 at the time, but from these two, I chose 1 because if `until` is an optional parameter it is already implicit that it only applies if set.
