### ISSUE TITLE
Clear queue after disconnect

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#170]
## Rationale

The bot preserves its queue even if disconnected. This shouldn't happen because it leads to confusing situations like the bot being summoned already playing a track that was enqueued in the day before.

## Description

After leaving a voice channel (in all cases, be it a manual, an idle or a `/leave` disconnect), the queue should be cleared.

**Comment by afonsojramos** [comment]
This only happens in a manual or a `/leave` disconnect, right? Since the idle only happens when nothing is playing, right? Or did I misunderstand from the last PR #176?

**Comment by aquelemiguel** [comment]
AFAIK no disconnects are clearing the queue, so even if you queue a track, pause it and either have it idle disconnect or do it manually, when you re-summon it, the track will stay there. #176 is just ensuring the auto-disconnect works, not that the queue is getting flushed.

**Comment by afonsojramos** [comment]
What I meant is that it would never auto disconnect if it was playing music, but indeed if it is on pause it does retain the queue...

Food for thought, if someone accidentally disconnects the bot and quickly summon it back, should it retain the queue?

**Comment by aquelemiguel** [comment]
Good question, I don't really know? I guess for consistency, yeah?

**Comment by afonsojramos** [comment]
I'll take it as a "yeah it should clear the queue", even though the question was the other way around 😅 

The only reference to disconnects in Serenity's documentation has been [this](https://docs.rs/serenity/latest/serenity/gateway/enum.ConnectionStage.html#variant.Disconnected), which I'm not sure if it applies.

**Comment by aquelemiguel** [comment]
Yeah, my bad, I got it backwards. I probably think it should clear.
