### ISSUE TITLE
Command permission update procedure has changed

### ISSUE THREAD

**Issue by StaticRocket** [aquelemiguel/parrot#196]
### 📝 Description

Looks like discord updated the way command permissions are handled:
https://discord.com/developers/docs/change-log

Now it requires the use of a bearer token:
https://discord.com/developers/docs/topics/oauth2#client-credentials-grant

Serenity seems to have some level of support for this:
https://github.com/serenity-rs/serenity/blob/f82a16dae0c5b1910598115b264a66fb8182a340/src/model/application/oauth.rs#L11-L12

Not entirely sure about implementation though.

The bot seems to choke on these changes:
```
thread 'tokio-runtime-worker' panicked at 'failed to create command permission: Http(UnsuccessfulRequest(ErrorResponse { status_code: 403, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v9/applications/<>/guilds/<>/commands/<>/permissions", query: None, fragment: None }, error: DiscordJsonError { code: 20001, message: "Bots cannot use this endpoint", errors: [] } }))', src/handlers/serenity.rs:107:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'failed to create response: Serenity(Http(UnsuccessfulRequest(ErrorResponse { status_code: 404, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v9/interactions/<>/<>/callback", query: None, fragment: None }, error: DiscordJsonError { code: 10062, message: "Unknown interaction", errors: [] } })))', src/handlers/serenity.rs:462:18
```

Any command that requires permissions to use is currently unavailable.

### 🪜 Reproduction Steps

1. Spin up the docker images with required environment variables
2. Attempt to use any command that requires/sets it's own permissions

### ℹ Environment / Computer Info

- **Parrot version**: ` ghcr.io/aquelemiguel/parrot:latest`
- **Operating System**: ` ghcr.io/aquelemiguel/parrot:latest`

**Comment by joao-conde** [comment]
Thanks for the bug report @StaticRocket ! We'll take a look into it when possible.

**Comment by StaticRocket** [comment]
I'm taking a stab at it now but I wanted to make sure it was documented

**Comment by StaticRocket** [comment]
Actually while skimming through the information this doesn't seem like something we should be doing. Bearer tokens seem to be temporary access tokens to the bot creators account, in which we assume they have permissions required to edit guild settings. 

This will not always be true so maybe we should just remove command permissions by default and document the desired roles and such in the wiki.

**Comment by StaticRocket** [comment]
Jesus. Alright, they have removed the ability for bots to directly control permissions for each command. They instead have added granular control for this in the integrations panel for the server where the bot resides (this is good) and now have a way for the bot to suggest defaults (also good). Unfortunately they neglect to say just how this should be done moving forward: https://support.discord.com/hc/en-us/articles/4644915651095-Command-Permissions

**Comment by StaticRocket** [comment]
The solution to this issue should also address #146

**Comment by LiftedStarfish** [comment]
Hey, can somebody update the Wiki to reflect this change? The bot isn't working, and I think it's related to this, and the permissions set when creating the bot.
