### ISSUE TITLE
Customizable status

### ISSUE THREAD

**Issue by ArtifyCZ** [aquelemiguel/parrot#200]
### 🧐 Rationale

I think it would be great to be able to tell the bot what it should have in the status.
Now it has `LISTENING TO /PLAY`, but something like `WATCHING /PLAY` would be great too.

### 📝 Description

Customizable Discord status by setting an environment variable

### ➕ Additional Information & References

![image](https://user-images.githubusercontent.com/57506608/182077110-0a4b16fb-e248-4904-9b79-e1befdacc5e9.png)

**Comment by afonsojramos** [comment]
This is something that we do not plan to do for the time being.
