### ISSUE TITLE
The bot does not compile

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#227]
### 📝 Description

Title is pretty self explanatory :) 

### 🪜 Reproduction Steps

1. Try to run the CI

### ℹ Environment / Computer Info

GitHub Actions

### 📸 Screenshots

https://github.com/rafaeldamasceno/parrot/actions/runs/3765059132/jobs/6400242903

**Comment by afonsojramos** [comment]
This has to do with the new Rust version most likely. But I am checking the logs on my mobile so I might be wrong.

**Comment by blimp4242** [comment]
I'm experiencing the same issue, errors are also the same. Did you find a workaround?

**Comment by aquelemiguel** [comment]
Hi @rafaeldamasceno @blimp4242, I've looked into this and found it's related with [rspotify](https://crates.io/crates/rspotify).
I'm pushing a fix in a bit, bumping it to 0.11.6 and fixing the code accordingly, which should make the CI pass.

I am however really confused about how our CI is automatically assuming we're on the latest version of this crate...
Could you have a look at what's going on when you have time, @afonsojramos?

**Comment by aquelemiguel** [comment]
@blimp4242 @rafaeldamasceno Thank you for the patience and inputs. [v1.5.1](https://github.com/aquelemiguel/parrot/releases/tag/v1.5.1) is now out, which fixes this.
