### ISSUE TITLE
/managesources command does not save state upon bot restart

### ISSUE THREAD

**Issue by futiiile** [aquelemiguel/parrot#236]
### 📝 Description

If I edit the sources using the `/managesources` command, when the bot gets restarted it goes back to the default. (The reason I restart the bot often is because Spotify dies after a few hours of the bot being up ¯\\\_(ツ)_/¯)

### 🪜 Reproduction Steps

1. Run `/managesources`
2. Change some stuff
3. Restart bot
4. Run `/managesources` again

### ℹ Environment / Computer Info

- **Parrot version**: `1.5.1 `
- **Operating System**: `Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64) `

**Comment by aquelemiguel** [comment]
Hi and welcome, @futiiile! ✌️

Unfortunately, as of now there's still no mechanism for preserving state, which is what #124 tries to solve. Once that issue moves forward, allowed/blocked sources will be stored.

**Comment by afonsojramos** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/19473034/221610119-eb99e9d4-2c46-49ab-9ac8-c86727bb9d1b.png">
😞 😞 😞

**Comment by joao-conde** [comment]
:sweat_smile:  peer pressure working at its finest. Here baitolas: https://github.com/aquelemiguel/parrot/pull/237

**Comment by futiiile** [comment]
> Hi and welcome, @futiiile! ✌️
> 
> Unfortunately, as of now there's still no mechanism for preserving state, which is what #124 tries to solve. Once that issue moves forward, allowed/blocked sources will be stored.

Hello, thank you for the response!

I am glad to see it is being worked on. I hope you guys will also find a solution to keep Spotify alive during the whole time the bot is up. Good luck!

**Comment by joao-conde** [comment]
:disappointed: :disappointed: :disappointed: 

![image](https://user-images.githubusercontent.com/16060539/222474000-b35e0411-7ef5-4d8d-b5f5-4e419f5e7327.png)

**Comment by joao-conde** [comment]
@futiiile next release should contain the saving feature :) https://github.com/aquelemiguel/parrot/pull/237
