### ISSUE TITLE
Add voting system to `!skip` and introduce `!forceskip`

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#44]
In larger servers, there needs to be a voting system in place for skipping songs so the queue cannot be griefed.
This means performing the following changes:

- `!skip` / `!s` should no longer immediately skip a track but instead display a new reaction-based voting system where `x` votes (maybe other metric?) skip it.
- `!forceskip` / `!fs` should be restricted to members with a **DJ permission** and immediately skips the track. This is identical to the current behavior of `!skip`.

More on this **DJ permission** on a later issue because it should also be used by other destructive commands like `!clear` and `!remove` or even `!seek`.

**Comment by afonsojramos** [comment]
I'd like to take this issue after #115 is merged :eyes:
