### ISSUE TITLE
Allow prefix change

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#45]
Forcing users to use the `!` prefix can cause conflicts with other bots on the server.

Should this be an environment variable (easier but requires redeploying) or does it justify a whole new `!prefix` command usable only by admins (harder but allows for changing on the fly)? Requesting your inputs here, @afonsojramos and @joao-conde.

Regardless of the chosen approach:
* The bot's activity should also reflect the prefix change.
* Existing messages that reference the exclamation mark prefix should now use the current prefix.

**Comment by aquelemiguel** [comment]
@afonsojramos Any advancements on this? 🙂

**Comment by joao-conde** [comment]
I think this issue and the listening party mode both require storing simple data but that needs to be associated with the server that called the command. As we discussed, a single parrot instance can then be used by multiple servers. The way current commands work for parrot running in the current server, is by the received context (which allows us to extract the server and a lock to the parrot instance on that discord server).

For this prefix issue and for others, we want to store simple settings but only for the discord server that called it.
I think we need to discuss several approaches for this and then pick one, before moving on. The current one I think we mostly agree on would be to store something like a JSON file where for each server ID you store settings (like, prefix). But we should investigate more.

**Comment by afonsojramos** [comment]
I'm already mid-development on this, I just need some time to figure out the inner workings of serenity.

**Comment by aquelemiguel** [comment]
@afonsojramos What is the approach you've settled on?

**Comment by aquelemiguel** [comment]
> In theory, it should be easy by using [dynamic prefixes](https://docs.rs/serenity/latest/serenity/framework/standard/struct.Configuration.html#method.dynamic_prefix).

Good find, looks promising!
Joining your suggestions, I'd ask if this approach looks correct:

* Let a prefixes file map guild IDs to prefixes.
* When booting the bot, if this file already exists, import it into `context.data`. 
* If this specific guild could not be found in the context, use the default Serenity prefix `~`. Send a message prompting server owners to use the command `~prefix` to change it.
* Via `dynamic_prefix`, set a prefix based on the guild from which the message came from.
* Implement a `~prefix` command that both updates the context and the prefixes file with the new mapping.

**Comment by joao-conde** [comment]
Great, this is what I wanted: https://docs.rs/serenity/latest/serenity/client/struct.Client.html#structfield.data
Essentially we can store data and it is passed to each context, from what I understood. That solves the issues with `!autopause` command and `!prefix`. Except it does not guarantee persistency, i.e., when the bot is restarted. I would almost suggest we do it in separate issues and deal with persistence later. If not, we can solve it now by a simple JSON file, I think, because I dislike having a whole database layer added just for one setting right now.
