### ISSUE TITLE
Incorrect estimated time until play

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#46]
The estimated time until play is being calculated incorrectly - it should be the sum of the all the non-elapsed song durations before.
For instance, if song A is currently being played and is at `4:00 / 30:00` and song B is next and is `2:00` minutes long, then song C's estimated time until play should be `30:00 - 4:00 + 2:00 = 28:00`.

### Example

![image](https://user-images.githubusercontent.com/5618493/138459997-bff78d65-e69f-4167-ac58-8558db305255.png)

**Comment by aquelemiguel** [comment]
Hey @wang-edward, is this still being worked on? 🙂

**Comment by wang-edward** [comment]
> Hey @wang-edward, is this still being worked on? 🙂

no, sorry :(

**Comment by aquelemiguel** [comment]
> no, sorry :(

No need to apologize! I will have a look at this then, thank you. 😊
