### ISSUE TITLE
Restrict queue modifying commands to a DJ role

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#47]
Commands that perform modifications to the queue or make the bot connect/disconnect should be locked to a role or be put behind a voting system (relates to #44). As of writing, this is every command except for informative ones, which should stay unmodified:
- `now_playing`
- `queue`
- ~`genius/explain`~
- ~`genius/lyrics`~

If a user does not have said role and tries to use the command, a message informing their lack of permissions should be sent to the channel. A good discussion point would be how to tell the bot which role is the DJ role (relates to #45's discussion about where to store the prefix).

**Comment by Antonio-Bennett** [comment]
Hey @aquelemiguel :) for this implementation how would you go about adding the role to a user. I know serenity has the User type and it can have flags but there isn't a DJ flag or anything. There is a moderator flag etc, however. https://docs.rs/serenity/0.10.9/serenity/model/user/struct.UserPublicFlags.html What were your thoughts on this?

**Comment by Antonio-Bennett** [comment]
Hey @aquelemiguel @joao-conde I made this pull request that enables this functionality

**Comment by joao-conde** [comment]
Hey @Antonio-Bennett !  We will be reviewing this ASAP and requesting changes or approving it right away. Thanks!

**Comment by Antonio-Bennett** [comment]
Hey @joao-conde :) Thanks for the quick reply! For sure let me know if anything needs to change it was fun figuring this one out :)

**Comment by aquelemiguel** [comment]
Don't know how to use it but this looks like the new way to [set permissions for application commands](https://docs.rs/serenity/latest/serenity/builder/struct.CreateApplicationCommandsPermissions.html#). Could be useful.

**Comment by joao-conde** [comment]
Yup, I am going to use that, I discussed it in Serenity's discord
