### ISSUE TITLE
Chain commands

### ISSUE THREAD

**Issue by joao-conde** [aquelemiguel/parrot#49]
## Rationale

Chaining commands allows for faster and easier use of the bot.

## Description

Commands should be able to be chained using some kind of `and` operator, sort of like Unix's `&&`. One could copy-paste a chain of commands and use that. 

For example, suppose you want to pause, go to the start of the track and resume it. You would have to type and enter each of the following:

`!pause` + `!seek 00:00` + `!resume`

The idea of this feature is to have the following syntax:

`!pause && !seek 00:00 && !resume`

**Note** that here I used the `&&` Unix and operator, but we could use a more friendly operator like `+`.

**Comment by aquelemiguel** [comment]
Great idea, good for manipulating the queue quickly.
I'd suggest `&&` as well, it should conflict the least with other commands.

**Comment by joao-conde** [comment]
Starting to think this may not be as useful as I initially thought (especially after implementing `!autopause` for listening parties). I am in favor of closing, but maybe one of you grew fond of the feature @afonsojramos or @aquelemiguel ?

**Comment by aquelemiguel** [comment]
In theory I like the idea but I'm thinking it might be extra tough to implement. Imagine `~play && ~seek`, how would we go about waiting until the song gets queued? I'm fine with closing.

**Comment by joao-conde** [comment]
I anticipate an ugly solution that will not add much value. Closing for now.
