### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by rafaeldamasceno** [aquelemiguel/parrot#50]
## Rationale

Most people use Spotify to listen to tracks. They also usually have playlists on Spotify. It would be nice to have support for on-the-fly conversion of Spotify links.

## Description

When a Spotify link is given, fetch the artist and title of the track (or tracks, in the case of a playlist), and then feed them into `ytdl_search` as usual.

**Comment by afonsojramos** [comment]
I'm going to tackle this next, if no one opposes!

**Comment by aquelemiguel** [comment]
I'm currently doing some refactoring in [`source-getters`](https://github.com/aquelemiguel/parrot/tree/source-getters) that prepares for implementations in both #15 and #50. I'd suggest either waiting or continuing work on that branch before tackling this.
