### ISSUE TITLE
Add pagination system

### ISSUE THREAD

**Issue by aquelemiguel** [aquelemiguel/parrot#53]
## Rationale

Right now, there are a few commands that require a pagination system.
`!queue` already has it and the code for it is relatively large. It'd be great to generalize this system for usage in other commands.

## Description

The response from Genius commands `!explain` and `!lyrics` can exceed the maximum size of the embed (especially the lyrics). If it does, the response should be split into multiple pages. A user can switch to a different page via reactions.

## Reference

See #19 implementation.

**Comment by afonsojramos** [comment]
Wouldn't this mean that we would need to constantly update the message? 

I can try and tackle this one 👀

**Comment by afonsojramos** [comment]
Closing this as the genius API was deprecated in `v1.0.0`. Let me know if I'm wrong! ✌️
