### ISSUE TITLE
Auto leave / join

### ISSUE THREAD

**Issue by StaticRocket** [aquelemiguel/parrot#54]
## Rationale

If the bot is the only thing in a voice channel it should automatically stop playback and disconnect to save resources. If the bot is kicked from the voice channel or leaves on it's own a play command should automatically summon it, assuming it's not already in another channel.

## Description

Automatically disconnect the bot if it's the only thing in a voice channel (either immediately or after a set time). Add a summon hook to the play command.

**Comment by aquelemiguel** [comment]
Hi @StaticRocket, this is a great idea! 🤗

The play command actually already has a summon hook, but is a little busted right now (#21) - if the bot leaves the channel, it'll struggle to rejoin. Running the summon command usually fixes it.

A follow-up question: should the bot also automatically leave the channel if it hasn't played any songs for a few minutes? Maybe we could also save bandwidth there.

**Comment by StaticRocket** [comment]
I was thinking about that, considering other bots have that feature, but I also thing that feature could be more annoying than useful if the timeout is too low/high. Maybe if this is exposed in the environment file with a value of 0 to disable the feature?

**Comment by aquelemiguel** [comment]
I'd maybe simplify and start with a default timeout of something like 10 minutes of the queue being empty.
Then after #45 is closed, we can think about the best way to change this timeout.

**Comment by joao-esteves** [comment]
I don't like how Hydra quickly disconnects when it's not playing a song. I like that Parrot doesn't implement this, however, a very high timeout could be okay.
