### ISSUE TITLE
Unresponsiveness with long songs

### ISSUE THREAD

**Issue by danrpinho** [aquelemiguel/parrot#88]
## Description

When playing long songs, such as radios or playlists (which usually run about an hour long), the bot suddenly stops playing audio and stops responding to commands.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The song plays until the end, and users can input commands. |
| **Observed** | The audio playback stops (around the 30-minute mark) and the bot does not respond to commands. |

## Repro Steps

1. `!play` a long video (for example, [this one](https://www.youtube.com/watch?v=syK3EZpi1sw&t=4s))
2. Listen until the video ends
3. Attempt to add commands later in the video's runtime

## Environment

| Key | Value |
| --- | --- |
| **Operating System** | Ubuntu 21.10 impish |
| **Kernel** | x86_64 Linux 5.13.0-23-generic |
| **CPU** | Intel Core i5-6500 @ 4x 3,6GHz [22.0°C] |
| **RAM** | 7866MiB / 15893MiB |

**Comment by afonsojramos** [comment]
I can confirm that this happens as well. I haven't had many occasions where I listened to long videos, however, everytime that I have, it has stalled at some point.

Ps: I think this is unrelated to the Windows bug that we've discovered the other day @aquelemiguel @joao-conde

**Comment by aquelemiguel** [comment]
I think it just might.
Now that I think of it, we're getting songbird directly from their current branch because of yt-dlp compatibility:

```
[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
features = ["builtin-queue", "yt-dlp"]
```

I wonder if something wrong was pushed. I'm 99.99% certain it isn't our code but a dependency.

**Comment by aquelemiguel** [comment]
Thank you for the bug report, @danrpinho.

It just might, @afonsojramos, they seem too similar... 99.99% chance it's unrelated to our code however, given v0.2.0 is also failing now. Should most likely be some funky dependency on both issues. I'm still investigating this.

**Comment by afonsojramos** [comment]
The thing is that your case @aquelemiguel does not fail on Linux, and this one does. If it IS the same problem, it is much worse on Windows vs Linux.

**Comment by aquelemiguel** [comment]
It's the same issue, no? Only that on Windows it freezes after a minute or so and on Linux it's half an hour.

**Comment by rafaeldamasceno** [comment]
This issue is, sadly, a regression. 51a99370dcb26de7a13248024680d83c78299a59 is a good commit (and possibly the last if you say v0.2.0 is now failing).

**Comment by joao-conde** [comment]
@rafaeldamasceno  thanks for testing it <3 So you mean that commit works fine for you? Let us all test and double-check that. If that is confirmed, would that mean 2b7f635293842a30a5871882cc9b521f88a92b06 to e1c0249214d0b76b6cc2ad23f124f94592d8bf2e are the culprit? Let's test that as well.

**Comment by aquelemiguel** [comment]
> This issue is, sadly, a regression. [51a9937](https://github.com/aquelemiguel/parrot/commit/51a99370dcb26de7a13248024680d83c78299a59) is a good commit (and possibly the last, if you say v0.2.0 is now failing).

God's work, @rafaeldamasceno. 💖

I can also confirm [`51a9937`](https://github.com/aquelemiguel/parrot/commit/51a99370dcb26de7a13248024680d83c78299a59) is working on Windows and failing on [`2b7f635`](https://github.com/aquelemiguel/parrot/commit/2b7f635293842a30a5871882cc9b521f88a92b06) meaning that it was the transition from youtube-dl to yt-dlp. In order to get yt-dlp, we're getting the latest version of Songbird from their current branch:

```toml
# Cargo.toml
git = "https://github.com/serenity-rs/songbird"
branch = "current"
features = ["builtin-queue", "yt-dlp"]
```

**Comment by aquelemiguel** [comment]
Guys over at Serenity's Discord seem to have repro'd it.

![image](https://user-images.githubusercontent.com/5618493/149166671-ec9351c8-267e-4297-93e4-e5271c169bd4.png)

**Comment by joao-conde** [comment]
Seems to be this will be an easy fix 😄 Let us wait for a Serenity patch release and see. Preferably we should stop depending on the current branch, so if they do make a release with the fix, we should swap to the version.

**Comment by afonsojramos** [comment]
Waiting it out it is then 🤓 Awesome, thanks for contacting them directly @aquelemiguel!

**Comment by aquelemiguel** [comment]
No fucking way, I think I got it.
