### ISSUE TITLE
Queue commands stop working while a livestream is in the queue

### ISSUE THREAD

**Issue by danrpinho** [aquelemiguel/parrot#94]
## Description

Adding a livestream (for example, a music radio) to the queue makes some commands stop working. The `/play` command stops showing which video was added to the queue (even if the video has a fixed length), while `/queue` and `/np` show error messages. The `/skip` command functions as expected, and the commands start working again after livestream playback ends.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The bot showcases the current playing song and other videos in the queue. |
| **Observed** | The bot sends an error message to the user's Discord client with the message "The application did not respond." |

## Repro Steps

1. `/play` two regular videos
2. Verify that the bot states which videos were added to the queue
3. Check that `/np` and `/queue` work properly
4. `/play` an ongoing livestream (for example, [this one](https://www.youtube.com/watch?v=5qap5aO4i9A))
5. Check that the bot only says "Searching..."
6. Verify that `/queue` throws an error message while `/np` functions as expected
7. `/play` a regular video
8. Verify that the bot does not say which video was added
9. `/skip` videos until the livestream starts
10. Verify that both `/np` and `/queue` throw error messages
11. `/skip` the livestream
12. Verify that `/play`, `/np` and `/queue` function normally (the first one with regular videos)

## Environment

| Key | Value |
| --- | --- |
| **Operating System** | Ubuntu 21.10 impish |
| **Kernel** | x86_64 Linux 5.13.0-23-generic |
| **CPU** | Intel Core i5-6500 @ 4x 3,6GHz |

**Comment by danrpinho** [comment]
After poking around with the bot's behaviour with @rafaeldamasceno, we found out that it is possible that the bot doesn't know how to handle videos without a fixed duration. All commands that stop working showcase the livestream's information:

- `/np` works with a regular song while the livestream is in the queue because it only shows that video;
- Both `/np` and `/queue` stop working while the livestream is playing because they both show information about the livestream;
- `/play` commands issued while the livestream is queued/playing do not function due to the "Estimated time until play" information. This is in conformity with our observation that all these three commands function normally after livestream playback ends.

**Comment by aquelemiguel** [comment]
@danrpinho Thank you for the report. 🙂
I repro'd this as well and converged on a few dangerous unwraps for `metadata.duration`. For example:

https://github.com/aquelemiguel/parrot/blob/fd2a0c08984b790f9468fb74eb37c5930abc4b59/src/commands/queue.rs#L131-L135

The duration field isn't set for livestreams so we should handle the `Option` instead of unwrapping.

**Comment by rafaeldamasceno** [comment]
@aquelemiguel Is there any way you can set +∞ for the value of the duration of livestreams when handling the `Option`? Floating point arithmethic should work fine (adding to infinity should return infinity as well), and then maybe rendering a cute ∞ on /np, /play (estimated time until play), and /queue?

**Comment by aquelemiguel** [comment]
@rafaeldamasceno I'm in favour of a cute ∞. 😊
